// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
namespace TicTacToe.Data.Migrations

{
    public partial class RemovedMiddleName : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "MiddleName",
                table: "Users");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "MiddleName",
                table: "Users",
                nullable: true);
        }
    }
}
